"""
plant_info.py

A mapping of plant/common names (matching the `dataset/` folders) to a small
metadata dictionary. Fields are intentionally minimal so the file can be
extended later from authoritative sources.

Helper functions are provided to access the mapping programmatically.
"""

from typing import Dict, List, Optional

BOTANICAL_DATA: Dict[str, Dict[str, object]] = {
    "Ajwain": {
        "scientific_name": "Trachyspermum ammi",
        "family": "Apiaceae",
        "origin": "Middle East/India",
        "phytochemical_compounds": "Thymol, carvacrol, p-cymene, terpinene",
        "pharmacological_properties": "Carminative, antimicrobial, antispasmodic, stimulant",
        "medicinal_use": "Gastrointestinal support, respiratory comfort, traditional digestive aid",
        "diseases_treated": "Indigestion, flatulence, abdominal pain, common cold, asthma symptoms",
        "parts_used": "Seeds (Fruits)",
        "preparation_method": "Crushed seeds in warm water, infusion, or culinary spice",
        "precautions": "Use in culinary amounts; avoid large medicinal doses during pregnancy without medical advice",
    },
    "Alocasia plant": {
        "scientific_name": "Alocasia macrorrhizos",
        "family": "Araceae",
        "origin": "Tropical Asia",
        "phytochemical_compounds": "Calcium oxalate crystals, alocasin, flavonoids",
        "pharmacological_properties": "Traditionally used as dynamic anti-inflammatory and antiseptic (after processing)",
        "medicinal_use": "External application for joint pain, leaf juice for skin irritations",
        "diseases_treated": "Arthritis, eczema, wound healing (traditional processed use only)",
        "parts_used": "Rhizomes, leaves (after extreme processing)",
        "preparation_method": "Cooked rhizomes or processed leaf juice for topical use",
        "precautions": "Contains irritant crystals — toxic if chewed raw; requires expert processing",
    },
    "Aloe Plant": {
        "scientific_name": "Aloe barbadensis Miller",
        "family": "Asphodelaceae",
        "origin": "Arabian Peninsula",
        "phytochemical_compounds": "Aloin, acemannan, various polysaccharides, anthraquinones",
        "pharmacological_properties": "Anti-inflammatory, immunomodulatory, wound-healing acceleration",
        "medicinal_use": "Dermatological recovery, digestive support, moisturizing agent",
        "diseases_treated": "Skin burns, psoriasis, constipation (oral), dry skin",
        "parts_used": "Leaves (inner gel and latex)",
        "preparation_method": "Fresh gel application, juice, or dried latex powder",
        "precautions": "Use topical products as directed; oral aloe preparations can have laxative effects and should be used cautiously",
    },
    "Amapalya": {
        "scientific_name": "Momordica charantia",
        "family": "Cucurbitaceae",
        "origin": "Tropical regions of Asia, Africa, and Caribbean",
        "phytochemical_compounds": "Charantin, momordicin, polypeptide-p",
        "pharmacological_properties": "Hypoglycemic, antioxidant, antimicrobial, antiviral",
        "medicinal_use": "Blood sugar management, immune support, digestive health",
        "diseases_treated": "Diabetes mellitus, respiratory infections, intestinal worms, skin diseases",
        "parts_used": "Fruit, leaves, seeds",
        "preparation_method": "Juice from fresh fruit, decoction of leaves, or cooked vegetable",
        "precautions": "Avoid during pregnancy as it may cause uterine contractions; may lower blood sugar too much if taken with diabetes meds",
    },
    "Angelica": {
        "scientific_name": "Angelica archangelica",
        "family": "Apiaceae",
        "origin": "Europe and Asia",
        "phytochemical_compounds": "Furanocoumarins (angelicin), essential oils, valeric acid",
        "pharmacological_properties": "Carminative, antispasmodic, mild expectorant",
        "medicinal_use": "Digestive comfort, respiratory health, loss of appetite",
        "diseases_treated": "Indigestion, flatulence, bronchitis, rheumatic pains (topical)",
        "parts_used": "Root, seeds, leaves",
        "preparation_method": "Root decoction, herbal tea (infusion), or tincture",
        "precautions": "May increase photosensitivity in some individuals due to furanocoumarins",
    },
    "Barberry": {
        "scientific_name": "Berberis vulgaris",
        "family": "Berberidaceae",
        "origin": "Europe, Asia, and North Africa",
        "phytochemical_compounds": "Berberine, berbamine, oxyacanthine",
        "pharmacological_properties": "Traditionally considered antimicrobial, anti-inflammatory, and hepatoprotective",
        "medicinal_use": "Liver support, digestive health, minor infection management",
        "diseases_treated": "Diarrhea, indigestion, skin irritations, urinary tract infections (traditional)",
        "parts_used": "Bark (root and stem), berries",
        "preparation_method": "Decoction of bark, infusion of dried berries",
        "precautions": "Avoid high doses during pregnancy; consult a professional for medicinal use",
    },
    "Basil": {
        "scientific_name": "Ocimum basilicum",
        "family": "Lamiaceae",
        "origin": "Central Africa/Asia",
        "phytochemical_compounds": "Eugenol, linalool, methyl chavicol, estragaol",
        "pharmacological_properties": "Aromatic, mild anti-inflammatory, antioxidant, digestive support",
        "medicinal_use": "Digestive aid, culinary flavoring, aromatherapy for stress",
        "diseases_treated": "Stomach cramps, common cold, loss of appetite, insect bites",
        "parts_used": "Leaves, flowering tops",
        "preparation_method": "Fresh leaves in food, infusion (tea), or steam distillation for oil",
        "precautions": "Generally safe in food amounts; concentrated essential oils should be used with care",
    },
    "Beechh Tree": {
        "scientific_name": "Fagus sylvatica",
        "family": "Fagaceae",
        "origin": "Temperate Europe, Asia, and North America",
        "phytochemical_compounds": "Tannins, creosote (from wood), phenolic compounds",
        "pharmacological_properties": "Traditionally considered astringent, antiseptic (tar/creosote), and mild expectorant",
        "medicinal_use": "Skin irritations (external), respiratory support (historical tar use)",
        "diseases_treated": "Wounds, skin infections, mild coughs (traditional)",
        "parts_used": "Bark, leaves, nuts",
        "preparation_method": "Decoction of bark for washing, or leaf infusion",
        "precautions": "Bark and seeds contain fagine; seeds can be toxic in large quantities",
    },
    "Belladonna": {
        "scientific_name": "Atropa belladonna",
        "family": "Solanaceae",
        "origin": "Europe, North Africa, and Western Asia",
        "phytochemical_compounds": "Tropane alkaloids (atropine, hyoscyamine, scopolamine)",
        "pharmacological_properties": "Powerful anticholinergic, sedative, antispasmodic",
        "medicinal_use": "Modern pharmaceutical source; historically used for eye dilation and pain (highly regulated)",
        "diseases_treated": "Motion sickness, GI spasms, overactive bladder (as pharmaceutical extracts)",
        "parts_used": "Leaves, root",
        "preparation_method": "Highly controlled pharmaceutical extraction only",
        "precautions": "Highly toxic — do not use without professional medical supervision",
    },
    "Betel leaf": {
        "scientific_name": "Piper betle",
        "family": "Piperaceae",
        "origin": "Southeast Asia",
        "phytochemical_compounds": "Eugenol, chavibetol, hydroxychavicol, various polyphenols",
        "pharmacological_properties": "Antiseptic, anti-inflammatory, traditional stimulant, carminative",
        "medicinal_use": "Oral hygiene, digestive support, cough suppression (traditional)",
        "diseases_treated": "Bad breath, indigestion, respiratory congestion, localized inflammation",
        "parts_used": "Leaves",
        "preparation_method": "Fresh leaf juice, or chewing fresh leaf with lime (traditionally)",
        "precautions": "Chewing with tobacco or areca nut has known carcinogen risks",
    },
    "Black walnuts": {
        "scientific_name": "Juglans nigra",
        "family": "Juglandaceae",
        "origin": "Eastern North America",
        "phytochemical_compounds": "Juglone, tannins, flavonoids, iodine",
        "pharmacological_properties": "Historically used as antifungal, vermifuge (parasite killer), and antiseptic",
        "medicinal_use": "Parasite management (hull), skin fungal issues (topical hull extracts)",
        "diseases_treated": "Intestinal parasites, ringworm, athlete's foot, skin sores",
        "parts_used": "Fruit hull (outer shell), leaves, inner bark",
        "preparation_method": "Tincture or decoction of green hulls for internal/external use",
        "precautions": "Hull extract may cause allergic reactions or contact dermatitis in some; internal use should be limited",
    },
    "Brahmi": {
        "scientific_name": "Bacopa monnieri",
        "family": "Plantaginaceae",
        "origin": "India and wetlands globally",
        "phytochemical_compounds": "Bacoside A and B, saponins, alkaloids",
        "pharmacological_properties": "Cognitive enhancement, neuroprotective, antioxidant, adaptogenic",
        "medicinal_use": "Memory support, concentration improvement, stress reduction",
        "diseases_treated": "Memory loss, anxiety, ADHD (supportive), learning disabilities",
        "parts_used": "Whole plant",
        "preparation_method": "Infusion (tea), capsules, or fresh juice in clarified butter (Ayurvedic)",
        "precautions": "May cause nausea or digestive upset in some; consult practitioner for therapeutic dosing",
    },
    "California": {
        "scientific_name": "Eschscholzia californica (California Poppy)",
        "family": "Papaveraceae",
        "origin": "Western North America",
        "phytochemical_compounds": "Alkaloids (protopine, allocryptopine, californidine)",
        "pharmacological_properties": "Mild sedative, anxiolytic, analgesic (traditional)",
        "medicinal_use": "Sleep support, anxiety management, mild pain relief",
        "diseases_treated": "Insomnia, nervous tension, toothache (historical)",
        "parts_used": "Whole plant (above-ground parts)",
        "preparation_method": "Infusion (tea), tincture, or liquid extract",
        "precautions": "Avoid use with other sedatives; consult professional before use",
    },
    "Coriander": {
        "scientific_name": "Coriandrum sativum",
        "family": "Apiaceae",
        "origin": "Southern Europe, North Africa, and SW Asia",
        "phytochemical_compounds": "Linalool, geraniol, cineole, fatty acids",
        "pharmacological_properties": "Carminative, digestive, antioxidant, traditional lipid-lowering potential",
        "medicinal_use": "Digestive aid, culinary flavoring, heavy metal detox support (folk claim)",
        "diseases_treated": "Bloating, loss of appetite, indigestion, skin rashes (topical seeds)",
        "parts_used": "Seeds (Fruits), leaves",
        "preparation_method": "Infusion of crushed seeds, or fresh leaves in culinary dishes",
        "precautions": "Generally safe in food amounts; some individuals may have a genetic distaste or mild allergy",
    },
    "Corn flower": {
        "scientific_name": "Centaurea cyanus",
        "family": "Asteraceae",
        "origin": "Europe",
        "phytochemical_compounds": "Anthocyanins (protocyanin), flavonoids, sesquiterpene lactones",
        "pharmacological_properties": "Mild astringent, anti-inflammatory, soothing",
        "medicinal_use": "Eye soothing (as wash), mild tonic, skin soothing",
        "diseases_treated": "Conjunctivitis (traditional wash), mild skin irritations",
        "parts_used": "Flower heads",
        "preparation_method": "Sterile infusion (standardized) for eye wash, or tea",
        "precautions": "Avoid concentrated use in eyes without sterile preparation; possible allergy to Asteraceae",
    },
    "Curry leaves": {
        "scientific_name": "Murraya koenigii",
        "family": "Rutaceae",
        "origin": "Indian subcontinent",
        "phytochemical_compounds": "Carbazole alkaloids (mahanimbine), essential oils",
        "pharmacological_properties": "Antioxidant, antimicrobial, traditionally used for lipid management",
        "medicinal_use": "Digestive support, hair health (topical oil), culinary flavoring",
        "diseases_treated": "Indigestion, diarrhea, hair loss (traditional)",
        "parts_used": "Leaves, root, bark",
        "preparation_method": "Fresh leaves in cooking, or leaf juice for medicinal use",
        "precautions": "Generally safe in food amounts",
    },
    "Fewer few": {
        "scientific_name": "Tanacetum parthenium (Feverfew)",
        "family": "Asteraceae",
        "origin": "Balkans, now widespread",
        "phytochemical_compounds": "Parthenolide, sesquiterpene lactones",
        "pharmacological_properties": "Anti-inflammatory, inhibition of platelet aggregation",
        "medicinal_use": "Migraine prevention, reduction of inflammation",
        "diseases_treated": "Migraine headaches, arthritis, fever (historical)",
        "parts_used": "Leaves (above-ground parts)",
        "preparation_method": "Dried leaf capsules, or infusion (tea)",
        "precautions": "Can cause mouth ulcers in some; avoid in pregnancy and with blood thinners",
    },
    "Veronica": {
        "scientific_name": "Veronica officinalis",
        "family": "Plantaginaceae",
        "origin": "Europe and Western Asia",
        "phytochemical_compounds": "Iridoid glycosides, flavonoids, tannins",
        "pharmacological_properties": "Expectorant, tonic, mild anti-inflammatory",
        "medicinal_use": "Respiratory support, skin health (traditional)",
        "diseases_treated": "Coughs, bronchitis, skin rashes (historical)",
        "parts_used": "Flowering herb",
        "preparation_method": "Infusion (tea) or liquid extract",
        "precautions": "Information limited; consult professional before use",
    },
    "Garlic": {
        "scientific_name": "Allium sativum",
        "family": "Amaryllidaceae",
        "origin": "Central Asia",
        "phytochemical_compounds": "Allicin, alliin, organosulfur compounds",
        "pharmacological_properties": "Anticmicrobial, cardiovascular support, antihypertensive",
        "medicinal_use": "Immune enhancement, circulation support, lipid management",
        "diseases_treated": "Common cold, hypertension (supportive), fungal infections",
        "parts_used": "Bulbs (cloves)",
        "preparation_method": "Raw crushed cloves, cooked, or oil-based maceration",
        "precautions": "Can interact with anticoagulant medications; stop before surgery",
    },
    "Gingko": {
        "scientific_name": "Ginkgo biloba",
        "family": "Ginkgoaceae",
        "origin": "China",
        "phytochemical_compounds": "Ginkgolides, bilobalide, flavonol glycosides",
        "pharmacological_properties": "Vasodilator, neuroprotective, antioxidant",
        "medicinal_use": "Cognitive support, circulation enhancement",
        "diseases_treated": "Memory impairment, peripheral vascular disease support",
        "parts_used": "Leaves (standardized extract preferred)",
        "preparation_method": "Standardized extract (capsules) or dried leaf tea",
        "precautions": "May interact with blood-thinning medications; risk of bleeding",
    },
    "Golden panthos": {
        "scientific_name": "Epipremnum aureum",
        "family": "Araceae",
        "origin": "Southeast Asia / Moorea",
        "phytochemical_compounds": "Calcium oxalate crystals",
        "pharmacological_properties": "Not characterized for medicinal use",
        "medicinal_use": "Primarily ornamental; air purification (atmospheric study)",
        "diseases_treated": "None (indoor air quality support only)",
        "parts_used": "None (ornamental usage only)",
        "preparation_method": "Atmospheric placement (indoor plant)",
        "precautions": "Toxic to many domestic pets and humans if ingested; causes mouth irritation",
    },
    "Hibiscus leaves": {
        "scientific_name": "Hibiscus sabdariffa / rosa-sinensis",
        "family": "Malvaceae",
        "origin": "Tropical regions worldwide",
        "phytochemical_compounds": "Anthocyanins, hibiscus acid, flavonoids",
        "pharmacological_properties": "Antioxidant, mild antihypertensive (flower focus)",
        "medicinal_use": "Cardiovascular support, cooling tonic, hair treatments",
        "diseases_treated": "High blood pressure (supportive), fever, hair loss (traditional)",
        "parts_used": "Flowers (calyces), leaves",
        "preparation_method": "Cold or hot infusion (tea), or leaf paste for hair",
        "precautions": "Generally safe as tea; may interact with some medications if taken in high doses",
    },
    "Horse Chestnuts": {
        "scientific_name": "Aesculus hippocastanum",
        "family": "Sapindaceae",
        "origin": "Balkan Peninsula",
        "phytochemical_compounds": "Aescin (triterpene saponins), flavonoids",
        "pharmacological_properties": "Venotonic, anti-edema, anti-inflammatory",
        "medicinal_use": "Venous circulation support (standardized extracts)",
        "diseases_treated": "Chronic venous insufficiency, varicose veins, hemorrhoids",
        "parts_used": "Seeds (extracts only)",
        "preparation_method": "Standardized clinical extracts (tablet/gel)",
        "precautions": "Raw seeds are toxic; use only standardized medicinal extracts",
    },
    "Horse tail": {
        "scientific_name": "Equisetum arvense",
        "family": "Equisetaceae",
        "origin": "Temperate Northern Hemisphere",
        "phytochemical_compounds": "Silica, alkaloids (equisetine), flavonoids",
        "pharmacological_properties": "Diuretic, remineralizing, mild astringent",
        "medicinal_use": "Urinary support, bone/hair/nail health (traditional)",
        "diseases_treated": "Edema, brittle nails, minor urinary tract irritations",
        "parts_used": "Sterile aerial stems (above-ground parts)",
        "preparation_method": "Infusion (tea) or decoction for minerals",
        "precautions": "Short-term use only; avoid in those with kidney disease or vitamin B1 deficiency",
    },
    "Indian beech": {
        "scientific_name": "Pongamia pinnata",
        "family": "Fabaceae",
        "origin": "Indian subcontinent / Southeast Asia",
        "phytochemical_compounds": "Karanjin, pongamol (flavonoids), fatty oils",
        "pharmacological_properties": "Antiseptic, anti-inflammatory, traditionally parasiticide",
        "medicinal_use": "Topical skin treatments, traditional veterinary uses",
        "diseases_treated": "Skin diseases (scabies, eczema), rheumatic pain (topical oil)",
        "parts_used": "Seeds (oil), leaves, bark",
        "preparation_method": "Expelled seed oil (Karanja oil) or leaf decoction",
        "precautions": "Not for internal consumption; oil is primarily for external/industrial use",
    },
    "Jack Fruit Leaves": {
        "scientific_name": "Artocarpus heterophyllus",
        "family": "Moraceae",
        "origin": "Western Ghats of India",
        "phytochemical_compounds": "Prenylflavonoids, tannins",
        "pharmacological_properties": "Antioxidant, traditional hypoglycemic potential",
        "medicinal_use": "Folk remedies for skin and blood sugar support",
        "diseases_treated": "Skin ulcers (charred leaf dressing), diabetes management (traditional claim)",
        "parts_used": "Leaves, fruit, root",
        "preparation_method": "Infusion (tea) of young eaves, or leaf ash for topical use",
        "precautions": "Information limited; use primarily as food/folk support",
    },
    "Jade tail": {
        "scientific_name": "Crassula ovata 'Gollum' (Jade Plant variant)",
        "family": "Crassulaceae",
        "origin": "South Africa",
        "phytochemical_compounds": "Flavonoids, malic acid (CAM metabolism)",
        "pharmacological_properties": "Traditionally considered for topical anti-inflammatory properties",
        "medicinal_use": "Minor skin irritations, ornamental/cultural significance",
        "diseases_treated": "Warts (folk remedy), nausea (historical tea - use extreme caution)",
        "parts_used": "Leaves",
        "preparation_method": "Fresh leaf juice applied topically",
        "precautions": "Generally considered non-toxic to humans, but can cause vomiting in cats and dogs",
    },
    "Lavender": {
        "scientific_name": "Lavandula angustifolia",
        "family": "Lamiaceae",
        "origin": "Mediterranean region",
        "phytochemical_compounds": "Linalool, linalyl acetate, terpinen-4-ol",
        "pharmacological_properties": "Anxiolytic, sedative, antimicrobial, anti-inflammatory",
        "medicinal_use": "Relaxation, sleep support, minor burn relief (essential oil)",
        "diseases_treated": "Anxiety, insomnia, skin irritations, headaches",
        "parts_used": "Flowering tops, leaves",
        "preparation_method": "Steam distillation for essential oil, or infusion (tea)",
        "precautions": "Use essential oils diluted; avoid ingestion of undiluted oils",
    },
    "Liquirice root": {
        "scientific_name": "Glycyrrhiza glabra",
        "family": "Fabaceae",
        "origin": "Southern Europe and Western Asia",
        "phytochemical_compounds": "Glycyrrhizin, isoliquiritigenin, flavonoids",
        "pharmacological_properties": "Demulcent, expectorant, anti-inflammatory, mild laxative",
        "medicinal_use": "Respiratory soothing, digestive support, flavoring agent",
        "diseases_treated": "Sore throats, gastric ulcers, adrenal exhaustion (supportive)",
        "parts_used": "Root, rhizome",
        "preparation_method": "Decoction of dried root, or powder",
        "precautions": "Large doses can affect blood pressure and potassium levels; avoid in pregnancy and hypertension",
    },
    "Malunggay": {
        "scientific_name": "Moringa oleifera",
        "family": "Moringaceae",
        "origin": "Indian subcontinent / Africa",
        "phytochemical_compounds": "Quercetin, chlorogenic acid, vitamins A/C/E, isothiocyanates",
        "pharmacological_properties": "Nutrient-dense, antioxidant, anti-inflammatory, traditionally hypoglycemic",
        "medicinal_use": "Direct nutritional support, lactation enhancement, immune boost",
        "diseases_treated": "Anemia, malnutrition, high blood pressure (supportive), inflammatory conditions",
        "parts_used": "Leaves, pods, seeds, root",
        "preparation_method": "Fresh leaves in food, dried leaf powder, or seed oil",
        "precautions": "Avoid large amounts of root/bark extracts during pregnancy",
    },
    "Mint": {
        "scientific_name": "Mentha × piperita / spicata",
        "family": "Lamiaceae",
        "origin": "Europe and Asia",
        "phytochemical_compounds": "Menthol, menthone, limonene, rosmarinic acid",
        "pharmacological_properties": "Antispasmodic, carminative, cooling, antimicrobial",
        "medicinal_use": "Digestive comfort, sinus relief, topical cooling",
        "diseases_treated": "Irritable Bowel Syndrome (IBS), tension headaches, nausea, nasal congestion",
        "parts_used": "Leaves, flowering tops",
        "preparation_method": "Infusion (tea) or steam distillation for essential oil",
        "precautions": "Avoid concentrated peppermint oil in infants; may worsen GERD in some",
    },
    "Mother wort": {
        "scientific_name": "Leonurus cardiaca",
        "family": "Lamiaceae",
        "origin": "Central Europe and Asia",
        "phytochemical_compounds": "Leonurine, stachydrine, iridoid glycosides",
        "pharmacological_properties": "Nervine, emmenagogue, hypotensive (traditional cardiac tonic)",
        "medicinal_use": "Nervous heart symptoms, reproductive system support",
        "diseases_treated": "Palpitations (anxiety-related), menstrual irregularities, nervous tension",
        "parts_used": "Above-ground flowering parts",
        "preparation_method": "Infusion (tea) or tincture",
        "precautions": "Avoid in pregnancy; may interact with heart medications",
    },
    "Neem": {
        "scientific_name": "Azadirachta indica",
        "family": "Meliaceae",
        "origin": "Indian subcontinent",
        "phytochemical_compounds": "Azadirachtin, nimbin, nimbidin, quercetin",
        "pharmacological_properties": "Antimicrobial, antifungal, insecticidal, anti-inflammatory",
        "medicinal_use": "Skin hygiene, dental health, internal immune support (traditional)",
        "diseases_treated": "Acne, gingivitis, fungal skin infections, intestinal parasites",
        "parts_used": "Leaves, seeds (oil), bark, twigs",
        "preparation_method": "Leaf paste, seed oil (topical), or twig for teeth cleaning",
        "precautions": "Avoid in children and during pregnancy; long-term internal use not advised",
    },
    "Papaya": {
        "scientific_name": "Carica papaya",
        "family": "Caricaceae",
        "origin": "Tropical Americas",
        "phytochemical_compounds": "Papain, chymopapain, carpaine, carotenoids",
        "pharmacological_properties": "Proteolytic (digestive), antioxidant, antimicrobial (seeds)",
        "medicinal_use": "Digestive aid, wound management (traditional enzyme use), nutrition",
        "diseases_treated": "Indigestion, edema, skin ulcers (traditional), nutritional deficiencies",
        "parts_used": "Fruit (ripe/unripe), leaves, seeds",
        "preparation_method": "Fresh fruit consumption, or leaf infusion (traditional fever use)",
        "precautions": "Unripe papaya latex is potent and can trigger uterine contractions; avoid in pregnancy",
    },
    "Periwinkle": {
        "scientific_name": "Catharanthus roseus",
        "family": "Apocynaceae",
        "origin": "Madagascar",
        "phytochemical_compounds": "Vincristine, vinblastine, ajmalicine",
        "pharmacological_properties": "Antitumor, hypoglycemic (historical), antihypertensive",
        "medicinal_use": "Source of critical oncology drugs; traditional use for metabolic support",
        "diseases_treated": "Hodgkin's lymphoma, leukemia (as purified drugs only); diabetes (folk claim)",
        "parts_used": "Whole plant",
        "preparation_method": "Pharmaceutical industrial extraction only",
        "precautions": "Extremely toxic if consumed directly; medicinal use must be pharmaceutical only",
    },
    "Ponytail palm palm": {
        "scientific_name": "Beaucarnea recurvata",
        "family": "Asparagaceae",
        "origin": "Eastern Mexico",
        "phytochemical_compounds": "Saponins, various steroidal components (limited study)",
        "pharmacological_properties": "Primarily ornamental; some studies on environmental toxin absorption",
        "medicinal_use": "Environmental air quality support",
        "diseases_treated": "None (indoor air quality support only)",
        "parts_used": "None (ornamental usage only)",
        "preparation_method": "Indoor placement (potted plant)",
        "precautions": "Non-toxic to cats and dogs; not for human medicinal consumption",
    },
    "Queen  annes  lace": {
        "scientific_name": "Daucus carota (Wild Carrot)",
        "family": "Apiaceae",
        "origin": "Europe and SW Asia",
        "phytochemical_compounds": "Carotol, daucol, beta-carotene (seeds/root)",
        "pharmacological_properties": "Diuretic, traditional emmenagogue, carminative",
        "medicinal_use": "Urinary support, folk reproductive remedies",
        "diseases_treated": "Gout (supportive), urinary stones (folk), digestive gas",
        "parts_used": "Seeds (Fruits), root",
        "preparation_method": "Infusion (tea) of seeds, or cooked root (as vegetable)",
        "precautions": "Risk of confusion with toxic Water Hemlock; seeds may have contraceptive properties (folk/study)",
    },
    "Rauwolfia": {
        "scientific_name": "Rauvolfia serpentina",
        "family": "Apocynaceae",
        "origin": "Indian subcontinent and East Asia",
        "phytochemical_compounds": "Reserpine, ajmaline, deserpidine",
        "pharmacological_properties": "Antihypertensive, antipsychotic, sedative",
        "medicinal_use": "Historical source for blood pressure medication",
        "diseases_treated": "Hypertension, mental disorders (agitation), snake bites (folk)",
        "parts_used": "Root",
        "preparation_method": "Pharmaceutical extraction (standardized medication)",
        "precautions": "Potent alkaloids; can cause severe depression and GI issues; use only by prescription",
    },
    "Rosemary": {
        "scientific_name": "Salvia rosmarinus",
        "family": "Lamiaceae",
        "origin": "Mediterranean region",
        "phytochemical_compounds": "Rosmarinic acid, carnosic acid, camphor, eucalyptol",
        "pharmacological_properties": "Antioxidant, cognitive stimulant, antimicrobial, circulatory aid",
        "medicinal_use": "Memory support, culinary flavoring, hair growth support (essential oil)",
        "diseases_treated": "Mental fatigue, alopecia (supportive), circulatory issues",
        "parts_used": "Leaves, flowering tops",
        "preparation_method": "Culinary use, infusion (tea), or hair oil maceration",
        "precautions": "Generally safe in food; avoid large medicinal doses in pregnancy/epilepsy",
    },
    "Rubber plant": {
        "scientific_name": "Ficus elastica",
        "family": "Moraceae",
        "origin": "Southeast Asia",
        "phytochemical_compounds": "Latex, terpenoids, flavonoids, ficin",
        "pharmacological_properties": "Traditionally anti-inflammatory and antimicrobial (bark/leaves in folk use)",
        "medicinal_use": "Primarily ornamental; folk remedies for minor wounds (latex - caution)",
        "diseases_treated": "Skin rashes (traditional), minor cuts (topical latex)",
        "parts_used": "Leaves, bark, latex",
        "preparation_method": "Fresh latex application (external only)",
        "precautions": "Latex can cause contact dermatitis and is toxic if ingested by pets; medicinal use is primarily historical/folk",
    },
    "Senna": {
        "scientific_name": "Senna alexandrina",
        "family": "Fabaceae",
        "origin": "North Africa and Middle East",
        "phytochemical_compounds": "Sennosides A and B (anthraquinone glycosides)",
        "pharmacological_properties": "Stimulant laxative, inhibition of water/electrolyte absorption in colon",
        "medicinal_use": "Short-term treatment of constipation, bowel clearance before surgery",
        "diseases_treated": "Acute constipation, bowel prep for clinical procedures",
        "parts_used": "Leaves, pods",
        "preparation_method": "Infusion (tea) or dried leaf capsules",
        "precautions": "Not for long-term use; can cause electrolyte imbalance and dependency; avoid in inflammatory bowel conditions",
    },
    "Slippery Elm": {
        "scientific_name": "Ulmus rubra",
        "family": "Ulmaceae",
        "origin": "North America",
        "phytochemical_compounds": "Mucilage (galactose, rhamnose), tannins, phytosterols",
        "pharmacological_properties": "Demulcent (soothing), antitussive, anti-inflammatory",
        "medicinal_use": "Sore throat relief, digestive membrane soothing",
        "diseases_treated": "Pharyngitis (sore throat), GERD (heartburn), minor GI irritations",
        "parts_used": "Inner bark",
        "preparation_method": "Powdered bark in hot water (slurry), lozenges, or capsules",
        "precautions": "Generally safe; may slow absorption of other oral medications due to mucilage coating",
    },
    "Snake plant": {
        "scientific_name": "Dracaena trifasciata",
        "family": "Asparagaceae",
        "origin": "West Africa",
        "phytochemical_compounds": "Saponins, alkaloids (limited study for medicinal use)",
        "pharmacological_properties": "Primarily valued for atmospheric air filtration",
        "medicinal_use": "Indoor air quality support; historical folk use for topical skin issues",
        "diseases_treated": "Sick Building Syndrome (atmospheric support), minor skin itch (traditional)",
        "parts_used": "Leaves",
        "preparation_method": "Indoor plant placement, or fresh leaf juice (traditional external)",
        "precautions": "Mildly toxic to pets if ingested; primarily an ornamental air purifier",
    },
    "Swiss plant": {
        "scientific_name": "Monstera deliciosa (Swiss Cheese Plant)",
        "family": "Araceae",
        "origin": "Central America",
        "phytochemical_compounds": "Calcium oxalate crystals",
        "pharmacological_properties": "Traditionally used for joint pain and snakebites in its native range (after processing)",
        "medicinal_use": "Primarily ornamental; native traditional arthritis support (roots)",
        "diseases_treated": "Arthritis (traditional root application), snakebites (historical folk use)",
        "parts_used": "Roots, leaves (extreme caution)",
        "preparation_method": "Processed root decoction for external use (traditional)",
        "precautions": "Contains irritant crystals; toxic to humans and pets if raw leaves/stems are ingested",
    },
    "Tea leaves": {
        "scientific_name": "Camellia sinensis",
        "family": "Theaceae",
        "origin": "East Asia",
        "phytochemical_compounds": "Polyphenols (EGCG), caffeine, L-theanine, flavonoids",
        "pharmacological_properties": "Antioxidant, stimulant, neuroprotective, thermogenic",
        "medicinal_use": "Focus and alertness, metabolic support, antioxidant boost",
        "diseases_treated": "Mental fatigue, oxidative stress, cardiovascular health support",
        "parts_used": "Leaves, leaf buds",
        "preparation_method": "Infusion (tea) with hot water",
        "precautions": "Caffeine content may cause jitters or sleep disruption in sensitive individuals",
    },
    "Terminalia leavees": {
        "scientific_name": "Terminalia arjuna / chebula (Arjun/Haritaki)",
        "family": "Combretaceae",
        "origin": "India and Southeast Asia",
        "phytochemical_compounds": "Arjunin, tannins, saponins, gallic acid",
        "pharmacological_properties": "Cardioprotective (Arjuna), digestive/tonic (Chebula)",
        "medicinal_use": "Ayurvedic heart support, digestive regularity",
        "diseases_treated": "Heart failure (supportive), hypertension, chronic diarrhea (Haritaki)",
        "parts_used": "Bark (Arjuna), Fruit (Haritaki)",
        "preparation_method": "Decoction (bark), or fruit powder (Haritaki)",
        "precautions": "Consult a professional; Arjuna may interact with conventional cardiac drugs",
    },
    "Thyme": {
        "scientific_name": "Thymus vulgaris",
        "family": "Lamiaceae",
        "origin": "Mediterranean",
        "phytochemical_compounds": "Thymol, carvacrol, linalool, rosmarinic acid",
        "pharmacological_properties": "Antimicrobial, antispasmodic, expectorant, antioxidant",
        "medicinal_use": "Cough and cold relief, oral hygiene, digestive support",
        "diseases_treated": "Bronchitis, sore throats, indigestion, localized skin infections",
        "parts_used": "Flowering tops, leaves",
        "preparation_method": "Infusion (tea), or steam distillation for essential oil",
        "precautions": "Concentrated thyme oil should be diluted; avoid large doses during pregnancy",
    },
    "Turmeric leaves": {
        "scientific_name": "Curcuma longa",
        "family": "Zingiberaceae",
        "origin": "South Asia",
        "phytochemical_compounds": "Curcumin, demethoxycurcumin, bisdemethoxycurcumin, essential oils",
        "pharmacological_properties": "Potent anti-inflammatory, antioxidant, hepatoprotective",
        "medicinal_use": "Joint health, digestive support, immune system modulation",
        "diseases_treated": "Arthritis, indigestion, metabolic syndrome (supportive), inflammatory conditions",
        "parts_used": "Rhizome",
        "preparation_method": "Dried powder in food, milk (Golden Milk), or capsules",
        "precautions": "May interact with blood thinners; high doses can cause GI upset",
    },
    "Winter Green": {
        "scientific_name": "Gaultheria procumbens",
        "family": "Ericaceae",
        "origin": "Eastern North America",
        "phytochemical_compounds": "Methyl salicylate, gaultherin",
        "pharmacological_properties": "Analgesic, rubefacient (warming), anti-inflammatory",
        "medicinal_use": "Topical pain relief for muscles and joints",
        "diseases_treated": "Muscle aches, arthritis pain, lower back pain (topical)",
        "parts_used": "Leaves",
        "preparation_method": "Steam distillation (oil), or leaf maceration in oil",
        "precautions": "Methyl salicylate is toxic in high doses; avoid if allergic to aspirin; do not use on broken skin",
    },
    "yellow dock": {
        "scientific_name": "Rumex crispus",
        "family": "Polygonaceae",
        "origin": "Europe and Western Asia",
        "phytochemical_compounds": "Anthraquinones (emodin), tannins, iron complexes (folk theory)",
        "pharmacological_properties": "Mild laxative, cholagogue (stimulates bile), alterative",
        "medicinal_use": "Liver and digestive support, traditional 'blood purifier' tonic",
        "diseases_treated": "Chronic constipation (mild), skin conditions related to digestion, anemia (folk)",
        "parts_used": "Root",
        "preparation_method": "Decoction (tea) of dried root, or tincture",
        "precautions": "Avoid in those with kidney stones (oxalates); avoid long-term internal use without advice",
    },
}


def list_plants() -> List[str]:
    """Return a sorted list of plant names available in the mapping."""
    return sorted(BOTANICAL_DATA.keys(), key=lambda s: s.lower())


def get_info(name: str) -> Optional[Dict[str, object]]:
    """Retrieve metadata for a plant by name.

    Performs a case-insensitive lookup. Returns None if not found.
    """
    # exact match
    if name in BOTANICAL_DATA:
        return BOTANICAL_DATA[name]

    # case-insensitive search
    lower = name.lower()
    for key in BOTANICAL_DATA:
        if key.lower() == lower:
            return BOTANICAL_DATA[key]

    return None


def search_by_keyword(keyword: str) -> List[str]:
    """Return plant names where the keyword appears in any metadata field."""
    k = keyword.lower()
    matches: List[str] = []
    for name, info in BOTANICAL_DATA.items():
        if k in name.lower():
            matches.append(name)
            continue
        
        # Check all string values in the info dictionary
        match_found = False
        for field_name, v in info.items():
            if isinstance(v, str) and k in v.lower():
                match_found = True
                break
            elif isinstance(v, list):
                if any(k in (str(u) or "").lower() for u in v):
                    match_found = True
                    break
        
        if match_found:
            matches.append(name)

    return matches


if __name__ == "__main__":
    # Quick sanity checks so this module can be run directly.
    plants = list_plants()
    print(f"Total plants in mapping: {len(plants)}")
    # show first 10 plants
    count = 0
    for p in plants:
        if count >= 10:
            break
        print(f" - {p}")
        count += 1
